/**
 * Partial English mirror of TEXT_CONSTANTS — populated only for keys added
 * after `feedback_bilingual_text` (2026-05-13) took effect. The full
 * English population of legacy keys is the responsibility of the i18n PR.
 *
 * Lookup contract: `TEXT_EN.<SECTION>.<KEY>` mirrors
 * `TEXT_CONSTANTS.<SECTION>.<KEY>`. Missing keys here fall back to the
 * Hebrew string at the call site (the runtime is not yet locale-aware).
 */
export const TEXT_EN = {
  AUTH: {
    WRONG_PASSWORD: 'Current password is incorrect.',
    PHONE_ALREADY_LINKED: 'This phone number is linked to another account. Contact a system administrator.',
  },
  SETTINGS: {
    CHANGE_PASSWORD: 'Change password',
    CHANGE_PASSWORD_TITLE: 'Change password',
    CHANGE_PASSWORD_DESCRIPTION: 'Enter your current password, then the new one.',
    CURRENT_PASSWORD: 'Current password',
    NEW_PASSWORD: 'New password',
    CONFIRM_NEW_PASSWORD: 'Confirm new password',
    PASSWORDS_MISMATCH: 'Passwords do not match.',
    PASSWORD_TOO_SHORT: 'Password must be at least 6 characters.',
    PASSWORD_UNCHANGED: 'New password must differ from current.',
    CHANGE_PASSWORD_SUBMIT: 'Update password',
    CHANGE_PASSWORD_SUBMITTING: 'Updating...',
    CHANGE_PASSWORD_SUCCESS: 'Password updated successfully.',
    CHANGE_PASSWORD_SIGN_OUT_OTHERS:
      'Sign out other devices after the password change (recommended).',
    SHOW_PASSWORD: 'Show password',
    HIDE_PASSWORD: 'Hide password',

    // Change-phone modal (PR-C)
    CHANGE_PHONE_TITLE: 'Change phone number',
    CHANGE_PHONE_DESCRIPTION: 'Re-enter your password, type the new number, then confirm with the SMS code.',
    CHANGE_PHONE_STEP_PREFLIGHT_TITLE: 'Before you start',
    CHANGE_PHONE_PREFLIGHT_INTRO: 'Changing your phone number affects your account security. Please note:',
    CHANGE_PHONE_PREFLIGHT_BULLET_SMS: 'An SMS verification code will be sent to the new number.',
    CHANGE_PHONE_PREFLIGHT_BULLET_REAUTH: 'Your current account password will be required.',
    CHANGE_PHONE_PREFLIGHT_BULLET_SESSIONS: 'Your other devices will be signed out and need to log in again.',
    CHANGE_PHONE_PREFLIGHT_BULLET_RATE_LIMIT: 'You can request one change per minute.',
    CHANGE_PHONE_PREFLIGHT_START: 'Start phone change',
    CHANGE_PHONE_STEP_REAUTH_TITLE: 'Confirm password',
    CHANGE_PHONE_STEP_NEW_NUMBER_TITLE: 'New phone number',
    CHANGE_PHONE_STEP_OTP_TITLE: 'Enter SMS code',
    CHANGE_PHONE_NEW_NUMBER_PLACEHOLDER: '+972501234567',
    CHANGE_PHONE_NEW_NUMBER_LABEL: 'New phone number (international format)',
    CHANGE_PHONE_OTP_LABEL: 'Code received via SMS',
    CHANGE_PHONE_RESEND_OTP: 'Resend code',
    CHANGE_PHONE_BACK_TO_STEP_NUMBER: 'Back — change number',
    CHANGE_PHONE_SUBMIT_NEW_NUMBER: 'Send SMS code',
    CHANGE_PHONE_SUBMIT_OTP: 'Confirm phone change',
    CHANGE_PHONE_SUBMITTING: 'Updating...',
    CHANGE_PHONE_SUCCESS: 'Phone number updated. Your other devices were signed out.',
    CHANGE_PHONE_SUCCESS_TITLE: 'Phone number updated',
    CHANGE_PHONE_SUCCESS_BODY:
      'The new number is saved. Your other devices will be signed out automatically on their next request to the server.',
    CHANGE_PHONE_SIGN_OUT_NOW_BUTTON: 'Sign out other devices now',
    CHANGE_PHONE_SIGN_OUT_NOW_SUBMITTING: 'Signing out...',
    CHANGE_PHONE_SIGN_OUT_NOW_DONE: 'Other devices signed out ✓',
    CHANGE_PHONE_SUCCESS_DONE: 'Done',
    CHANGE_PHONE_SAME_NUMBER: 'The new number matches the existing one — nothing to change.',
    CHANGE_PHONE_INVALID_E164: 'Phone number must be in international format (e.g. +972501234567).',
    CHANGE_PHONE_RATE_LIMITED: 'Try again in a moment. Only one change per minute is allowed.',
    CHANGE_PHONE_MIRROR_FAILED: 'Saving the new number on the server failed. Try again or contact support.',
    CHANGE_PHONE_GENERIC_ERROR: 'Phone number change failed. Try again.',

    // Delete-account modal (PR-G)
    DELETE_ACCOUNT_TITLE: 'Delete account',
    DELETE_ACCOUNT_WARNING_LONG: 'Your account will be flagged for deletion and permanently removed after 30 days. You can cancel within that window. All equipment and ammunition signed to you must be returned before deletion.',
    DELETE_ACCOUNT_REASON_LABEL: 'Reason (optional)',
    DELETE_ACCOUNT_REASON_PLACEHOLDER: 'Why are you deleting your account?',
    DELETE_ACCOUNT_SUBMIT: 'Confirm deletion',
    DELETE_ACCOUNT_SUBMITTING: 'Requesting deletion...',
    DELETE_ACCOUNT_SUCCESS: 'Deletion requested. Your account will be removed in 30 days — you can cancel any time from Settings.',
    DELETE_ACCOUNT_HAS_ASSETS: "Can't delete account — items are still signed to you. Return them first.",
    DELETE_ACCOUNT_ALREADY_REQUESTED: 'A deletion request is already pending for this account.',
    DELETE_ACCOUNT_GENERIC_ERROR: 'Deletion request failed. Try again.',
    DELETE_ACCOUNT_OUTSTANDING_HEADING: 'Outstanding items:',
    DELETE_ACCOUNT_OUTSTANDING_EQUIPMENT: 'Equipment signed',
    DELETE_ACCOUNT_OUTSTANDING_AMMUNITION: 'Ammunition signed',
    DELETE_ACCOUNT_OUTSTANDING_TRANSFERS: 'Open transfer requests',

    // Account Activity Section — credential audit log surfaced to the user
    ACCOUNT_ACTIVITY: 'Account activity',
    ACCOUNT_ACTIVITY_DESCRIPTION:
      'Recent security events on your account — password, phone, and account-deletion changes. If anything looks unfamiliar, contact a system administrator.',
    ACCOUNT_ACTIVITY_EMPTY: 'No security events yet.',
    ACCOUNT_ACTIVITY_LOADING: 'Loading activity...',
    ACCOUNT_ACTIVITY_ERROR: 'Failed to load activity.',
    ACCOUNT_ACTIVITY_RETRY: 'Try again',
    ACCOUNT_ACTIVITY_REFRESH: 'Refresh',
    ACCOUNT_ACTIVITY_IP: 'IP address',
    ACCOUNT_ACTIVITY_DEVICE: 'Device',
    ACCOUNT_ACTIVITY_ACTOR_SELF: 'by you',
    ACCOUNT_ACTIVITY_ACTOR_ADMIN: 'by a system administrator',
    ACCOUNT_EVENT_PASSWORD_CHANGED: 'Password changed',
    ACCOUNT_EVENT_PHONE_CHANGED: 'Phone number changed',
    ACCOUNT_EVENT_EMAIL_CHANGED: 'Email address changed',
    ACCOUNT_EVENT_PHONE_FORCE_RESET: 'Phone number reset by admin',
    ACCOUNT_EVENT_SESSIONS_REVOKED: 'Sessions revoked',
    ACCOUNT_EVENT_ACCOUNT_DELETION_REQUESTED: 'Account deletion requested',
    ACCOUNT_EVENT_ACCOUNT_DELETION_CANCELLED: 'Account deletion cancelled',
    ACCOUNT_EVENT_ACCOUNT_DELETED: 'Account deleted',

    // Revoke other sessions
    REVOKE_SESSIONS: 'Sign out other devices',
    REVOKE_SESSIONS_DESCRIPTION:
      'Signs out every other session on your account. Other devices will have to log in again. This device stays signed in.',
    REVOKE_SESSIONS_CONFIRM_TITLE: 'Sign out other devices?',
    REVOKE_SESSIONS_CONFIRM_BODY:
      'Other devices signed in to your account will need to log in again. This takes effect immediately.',
    REVOKE_SESSIONS_CONFIRM_SUBMIT: 'Sign out other devices',
    REVOKE_SESSIONS_CANCEL: 'Cancel',
    REVOKE_SESSIONS_SUBMITTING: 'Signing out...',
    REVOKE_SESSIONS_SUCCESS: 'Other devices signed out. They will be asked to log in again.',
    REVOKE_SESSIONS_ERROR: 'Sign-out failed. Try again.',
  },
  EQUIPMENT: {
    STATUS_AVAILABLE: 'Available',
    STATUS_SECURITY: 'In security',
    STATUS_REPAIR: 'In repair',
    STATUS_LOST: 'Lost',
    STATUS_PENDING_TRANSFER: 'Pending transfer',
    STATUS_EXCHANGE_REQUESTED: 'Exchange — awaiting approval',
    STATUS_STORED: 'Stored',
    STATUS_RETIRED: 'Returned to army',

    ARCHIVE: {
      SHOW_ACTIVE: 'Active equipment',
      SHOW_ARCHIVE: 'Archive',
      TOGGLE_ARIA: 'Toggle between active and archive views',
    },

    ROW_ACTIONS: {
      REPORT: 'Report',
      TRANSFER: 'Transfer',
      RETURN: 'Return',
      HISTORY: 'History',
      MORE: 'More actions',
      REQUEST_EXCHANGE: 'Request exchange',
      APPROVE_EXCHANGE: 'Approve exchange',
      REJECT_EXCHANGE: 'Reject exchange',
      REPLACE_BY_ANOTHER: 'Replace with another item',
      SEND_TO_STORAGE: 'Send to storage',
      PULL_FROM_STORAGE: 'Pull from storage',
    },

    EXCHANGE: {
      REQUEST_TITLE: 'Request exchange',
      REQUEST_DESCRIPTION: 'Describe why this item needs to be swapped. The signer will approve and assign a new serial.',
      APPROVE_TITLE: 'Approve exchange',
      APPROVE_DESCRIPTION: 'Enter the serial number of the new item that will replace this one.',
      REPLACE_TITLE: 'Replace with another item',
      REPLACE_DESCRIPTION: 'Replace this item with a new serial. The old item will be retired.',
      REJECT_TITLE: 'Reject exchange request',
      REJECT_DESCRIPTION: 'Enter a reason for rejecting the request.',
      REASON_LABEL: 'Reason',
      REASON_PLACEHOLDER: 'Enter a reason...',
      NEW_SERIAL_LABEL: 'New serial number',
      NEW_SERIAL_PLACEHOLDER: 'Enter serial number...',
      SUBMIT_REQUEST: 'Send request',
      SUBMIT_APPROVE: 'Approve and assign new serial',
      SUBMIT_REJECT: 'Reject request',
      SUBMIT_REPLACE: 'Perform exchange',
      CANCEL: 'Cancel',
      REQUEST_SUCCESS: 'Exchange request sent',
      APPROVE_SUCCESS: 'Exchange approved and new item created',
      REJECT_SUCCESS: 'Request rejected',
      REPLACE_SUCCESS: 'Item replaced successfully',
      VALIDATION_REASON_REQUIRED: 'Reason is required',
      VALIDATION_SERIAL_REQUIRED: 'Serial number is required',
      VALIDATION_SERIAL_TAKEN: 'This serial number already exists',
      PREDECESSOR_PILL: 'Created via exchange from {serial}',
    },

    STORAGE: {
      SEND_TITLE: 'Send to storage',
      SEND_DESCRIPTION: 'The item will be marked as stored and excluded from daily checks. It cannot be transferred while in storage.',
      SEND_SUBMIT: 'Send to storage',
      SEND_SUCCESS: 'Item sent to storage',
      PULL_TITLE: 'Pull from storage',
      PULL_DESCRIPTION: 'The item will return to available status.',
      PULL_SUBMIT: 'Pull from storage',
      PULL_SUCCESS: 'Item pulled from storage',
      ROUND_CLOSED_TOOLTIP: 'Round is closed — items cannot be pulled from storage right now',
      TRANSFER_BLOCKED_STORED_TOOLTIP: 'Item is in storage — pull from storage before transferring',
      INFO_BUBBLE_LABEL: 'Info',
    },

    SYSTEM_CONFIG: {
      ROUND_OPEN_LABEL: 'Round open',
      ROUND_OPEN_HELP: 'When enabled, users can pull items from storage. Turn off at the end of the round.',
    },

    REPORT_MODAL: {
      TITLE: 'Equipment report',
      SUBTITLE: 'Take a current photo and add a note.',
      NOTE_LABEL: 'Notes',
      NOTE_PLACEHOLDER: 'Working / item condition...',
      BYPASS_PHOTO: 'Report without a photo (limited permission)',
      CONDITION_LABEL: 'Item condition',
      CONDITION_OPTIONS: {
        GOOD: 'Good',
        NEEDS_REPAIR: 'Needs repair',
        WORN: 'Worn',
      },
      SUBMIT: 'Send report',
      CANCEL: 'Cancel',
      SUCCESS: 'Report submitted successfully',
      ERROR: 'Submitting the report failed',
    },

    HISTORY_PANEL: {
      TITLE: 'Action history',
      SUBTITLE: 'Full action log for the item',
      EMPTY: 'No history available',
      LOADING: 'Loading history...',
      CLOSE: 'Close',
      PREDECESSOR_BADGE: 'From predecessor item history',
      UNKNOWN_DATE: 'Unknown date',
      EXPAND_ROW_ARIA: 'Show more details',
      COLLAPSE_ROW_ARIA: 'Hide details',
      SOURCE_TRACKING: 'From item history',
      SOURCE_LOG: 'From action log',
      SOURCE_LABEL: 'Source',
      OWNER_DOC_LABEL: 'Item document',
      PREDECESSOR_FLAG_LABEL: 'From a predecessor item history',
      CONDITION_LABEL: 'Item condition',
    },

    ACTION_TYPES: {
      transfer_requested: 'Transfer requested',
      transfer_approved: 'Transfer approved',
      transfer_rejected: 'Transfer rejected',
      force_transfer_holder: 'Forced transfer (holder)',
      force_transfer_signer: 'Forced transfer (signer)',
      retirement_requested: 'Retirement requested',
      retirement_approved: 'Retirement approved',
      retirement_rejected: 'Retirement rejected',
      exchange_requested: 'Exchange requested',
      exchange_approved: 'Exchange approved',
      exchange_rejected: 'Exchange rejected',
      exchange_completed: 'Exchange completed',
      stored: 'Sent to storage',
      reissued: 'Pulled from storage',
      report_submitted: 'Report submitted',
      report_requested: 'Report requested',
      maintenance_start: 'Maintenance started',
      maintenance_complete: 'Maintenance completed',
      status_update: 'Status updated',
      condition_update: 'Condition updated',
      equipment_created: 'Equipment created',
      equipment_retired: 'Equipment retired',
      template_proposed: 'Template proposed',
      template_requested: 'Template requested',
      template_approved: 'Template approved',
      template_rejected: 'Template rejected',
      template_updated: 'Template updated',
      template_retired: 'Template retired',
      ammo_assigned_from_central: 'Ammo assigned from central',
      ammo_returned_to_central: 'Ammo returned to central',
      ammo_central_bulk_load: 'Ammo central bulk load',
      sign_in: 'Signed in',
      sign_out: 'Signed out',
      location_update: 'Location updated',
      notes_update: 'Notes updated',
    },

    CONDITION_LABELS: {
      good: 'Good',
      needs_repair: 'Needs repair',
      worn: 'Worn',
    },
  },
  PWA: {
    UPDATE_AVAILABLE_TITLE: 'New version available',
    UPDATE_AVAILABLE_BODY: 'An update is ready. The page will reload.',
    UPDATE_NOW: 'Update now',
    UPDATE_LATER: 'Later',
    CONFLICT_TITLE: 'Sync conflict',
    CONFLICT_BODY: 'The action tried to update an item that changed on the server after you went offline.',
    CONFLICT_KEEP_LOCAL: 'Force overwrite',
    CONFLICT_DISCARD: 'Discard action',
    CONFLICT_QUEUE_COUNT: 'remaining',
    CONFLICT_ROUTE_LABEL: 'Action',
  },
  PROFILE: {
    PHONE_NUMBER_LABEL: 'Phone number',
    TEAM: 'Team',
    ENLISTMENT_CYCLE: 'Enlistment cycle',
    ENLISTMENT_CYCLE_PLACEHOLDER: 'YYYY-MM',
    ADDRESS: 'Address',
    ADDRESS_PLACEHOLDER: 'City, street, house no.',
    EDIT_SECTION: 'Edit',
    EDIT_SECTION_ARIA: 'Edit section',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SAVING: 'Saving...',
    SAVED: 'Saved',
    SAVE_ERROR: 'Save failed. Try again.',
  },
  FEATURES: {
    AMMUNITION: {
      RECIPIENTS: {
        SECTION_TITLE: 'Ammunition managers',
        SECTION_DESCRIPTION:
          'Listed managers receive a notification for every ammunition report and can approve training plans.',
        EMPTY_STATE: 'No managers configured',
        ADD_PLACEHOLDER: 'Add manager...',
        EDIT: 'Edit',
        EDIT_ARIA: 'Edit ammunition managers',
        SAVE: 'Save',
        SAVING: 'Saving...',
        CANCEL: 'Cancel',
        REMOVE_ARIA: 'Remove manager',
        MAX_REACHED: 'Up to 10 managers',
        SAVE_ERROR: 'Saving the list failed. Try again.',
      },
    },
    ADMIN: {
      PERSONNEL: {
        TAB_LABEL: 'Personnel',
        SEARCH_PLACEHOLDER: 'Search by name or phone',
        FILTER_TOGGLE_ARIA: 'Toggle filters',
        FILTERS_ACTIVE_DOT_ARIA: 'Active filters',
        CLEAR_FILTERS: 'Clear',
        FILTER_RANK_LABEL: 'Rank',
        FILTER_RANK_PLACEHOLDER: 'All ranks',
        FILTER_USER_TYPE_LABEL: 'User type',
        FILTER_USER_TYPE_PLACEHOLDER: 'All types',
        FILTER_REGISTRATION_LABEL: 'Registration status',
        REG_ALL: 'All',
        REG_REGISTERED: 'Registered',
        REG_PENDING: 'Pending',
        SORT_LABEL: 'Sort',
        SORT_OPTIONS: {
          CREATED_DESC: 'Date (newest → oldest)',
          CREATED_ASC: 'Date (oldest → newest)',
          NAME_ASC: 'Name (A → Z)',
          NAME_DESC: 'Name (Z → A)',
          RANK_DESC: 'Rank (high → low)',
          RANK_ASC: 'Rank (low → high)',
        },
        EDIT: 'Edit',
        DELETE: 'Delete',
        SAVE: 'Save',
        CANCEL: 'Cancel',
        SAVING: 'Saving...',
        EXPAND_ARIA: 'Expand details',
        COLLAPSE_ARIA: 'Collapse details',
        ACTIONS_MORE_ARIA: 'More actions',
        REGISTERED_BADGE: 'Registered',
        PENDING_BADGE: 'Pending',
        REGISTRATION_DOT_ARIA: 'Registration status',
        FIELD_FIRST_NAME: 'First name',
        FIELD_LAST_NAME: 'Last name',
        FIELD_RANK: 'Rank',
        FIELD_PHONE: 'Phone number',
        FIELD_USER_TYPE: 'User type',
        FIELD_REGISTRATION: 'Registration status',
        FIELD_CREATED_AT: 'Added on',
        TOTAL: 'Total',
        FILTERED: 'Filtered',
        EMPTY_NO_PERSONNEL: 'No authorized personnel found. Add personnel first.',
        EMPTY_NO_RESULTS: 'No results match your filters.',
        LOADING: 'Loading personnel...',
        DELETE_CONFIRM_TITLE: 'Confirm deletion',
        DELETE_CONFIRM_MESSAGE: 'Remove {name} from the authorized personnel list?',
        DELETE_CONFIRM_BTN: 'Remove',
        DELETE_CONFIRM_CANCEL: 'Cancel',
        DELETE_CONFIRM_WARNING: 'Warning: this action cannot be undone.',
        NO_CHANGES: 'No changes were made',
        UPDATE_FAILED: 'Update failed. Try again.',
        VALIDATION_NAME: 'Name must contain only Hebrew letters, spaces, dashes (-) or apostrophes (\').',
        VALIDATION_RANK: 'Please select a rank.',
        VALIDATION_PHONE: 'Invalid phone number.',
      },
    },
  },
} as const;
