/**
 * Partial English mirror of TEXT_CONSTANTS — populated only for keys added
 * after `feedback_bilingual_text` (2026-05-13) took effect. The full
 * English population of legacy keys is the responsibility of the i18n PR.
 *
 * Lookup contract: `TEXT_EN.<SECTION>.<KEY>` mirrors
 * `TEXT_CONSTANTS.<SECTION>.<KEY>`. Missing keys here fall back to the
 * Hebrew string at the call site (the runtime is not yet locale-aware).
 */
export const TEXT_EN = {
  AUTH: {
    WRONG_PASSWORD: 'Current password is incorrect.',
    PHONE_ALREADY_LINKED: 'This phone number is linked to another account. Contact a system administrator.',
  },
  SETTINGS: {
    CHANGE_PASSWORD: 'Change password',
    CHANGE_PASSWORD_TITLE: 'Change password',
    CHANGE_PASSWORD_DESCRIPTION: 'Enter your current password, then the new one.',
    CURRENT_PASSWORD: 'Current password',
    NEW_PASSWORD: 'New password',
    CONFIRM_NEW_PASSWORD: 'Confirm new password',
    PASSWORDS_MISMATCH: 'Passwords do not match.',
    PASSWORD_TOO_SHORT: 'Password must be at least 6 characters.',
    PASSWORD_UNCHANGED: 'New password must differ from current.',
    CHANGE_PASSWORD_SUBMIT: 'Update password',
    CHANGE_PASSWORD_SUBMITTING: 'Updating...',
    CHANGE_PASSWORD_SUCCESS: 'Password updated successfully.',
    CHANGE_PASSWORD_SIGN_OUT_OTHERS:
      'Sign out other devices after the password change (recommended).',
    SHOW_PASSWORD: 'Show password',
    HIDE_PASSWORD: 'Hide password',

    // Change-phone modal (PR-C)
    CHANGE_PHONE_TITLE: 'Change phone number',
    CHANGE_PHONE_DESCRIPTION: 'Re-enter your password, type the new number, then confirm with the SMS code.',
    CHANGE_PHONE_STEP_PREFLIGHT_TITLE: 'Before you start',
    CHANGE_PHONE_PREFLIGHT_INTRO: 'Changing your phone number affects your account security. Please note:',
    CHANGE_PHONE_PREFLIGHT_BULLET_SMS: 'An SMS verification code will be sent to the new number.',
    CHANGE_PHONE_PREFLIGHT_BULLET_REAUTH: 'Your current account password will be required.',
    CHANGE_PHONE_PREFLIGHT_BULLET_SESSIONS: 'Your other devices will be signed out and need to log in again.',
    CHANGE_PHONE_PREFLIGHT_BULLET_RATE_LIMIT: 'You can request one change per minute.',
    CHANGE_PHONE_PREFLIGHT_START: 'Start phone change',
    CHANGE_PHONE_STEP_REAUTH_TITLE: 'Confirm password',
    CHANGE_PHONE_STEP_NEW_NUMBER_TITLE: 'New phone number',
    CHANGE_PHONE_STEP_OTP_TITLE: 'Enter SMS code',
    CHANGE_PHONE_NEW_NUMBER_PLACEHOLDER: '+972501234567',
    CHANGE_PHONE_NEW_NUMBER_LABEL: 'New phone number (international format)',
    CHANGE_PHONE_OTP_LABEL: 'Code received via SMS',
    CHANGE_PHONE_RESEND_OTP: 'Resend code',
    CHANGE_PHONE_BACK_TO_STEP_NUMBER: 'Back — change number',
    CHANGE_PHONE_SUBMIT_NEW_NUMBER: 'Send SMS code',
    CHANGE_PHONE_SUBMIT_OTP: 'Confirm phone change',
    CHANGE_PHONE_SUBMITTING: 'Updating...',
    CHANGE_PHONE_SUCCESS: 'Phone number updated. Your other devices were signed out.',
    CHANGE_PHONE_SUCCESS_TITLE: 'Phone number updated',
    CHANGE_PHONE_SUCCESS_BODY:
      'The new number is saved. Your other devices will be signed out automatically on their next request to the server.',
    CHANGE_PHONE_SIGN_OUT_NOW_BUTTON: 'Sign out other devices now',
    CHANGE_PHONE_SIGN_OUT_NOW_SUBMITTING: 'Signing out...',
    CHANGE_PHONE_SIGN_OUT_NOW_DONE: 'Other devices signed out ✓',
    CHANGE_PHONE_SUCCESS_DONE: 'Done',
    CHANGE_PHONE_SAME_NUMBER: 'The new number matches the existing one — nothing to change.',
    CHANGE_PHONE_INVALID_E164: 'Phone number must be in international format (e.g. +972501234567).',
    CHANGE_PHONE_RATE_LIMITED: 'Try again in a moment. Only one change per minute is allowed.',
    CHANGE_PHONE_MIRROR_FAILED: 'Saving the new number on the server failed. Try again or contact support.',
    CHANGE_PHONE_GENERIC_ERROR: 'Phone number change failed. Try again.',

    // Delete-account modal (PR-G)
    DELETE_ACCOUNT_TITLE: 'Delete account',
    DELETE_ACCOUNT_WARNING_LONG: 'Your account will be flagged for deletion and permanently removed after 30 days. You can cancel within that window. All equipment and ammunition signed to you must be returned before deletion.',
    DELETE_ACCOUNT_REASON_LABEL: 'Reason (optional)',
    DELETE_ACCOUNT_REASON_PLACEHOLDER: 'Why are you deleting your account?',
    DELETE_ACCOUNT_SUBMIT: 'Confirm deletion',
    DELETE_ACCOUNT_SUBMITTING: 'Requesting deletion...',
    DELETE_ACCOUNT_SUCCESS: 'Deletion requested. Your account will be removed in 30 days — you can cancel any time from Settings.',
    DELETE_ACCOUNT_HAS_ASSETS: "Can't delete account — items are still signed to you. Return them first.",
    DELETE_ACCOUNT_ALREADY_REQUESTED: 'A deletion request is already pending for this account.',
    DELETE_ACCOUNT_GENERIC_ERROR: 'Deletion request failed. Try again.',
    DELETE_ACCOUNT_OUTSTANDING_HEADING: 'Outstanding items:',
    DELETE_ACCOUNT_OUTSTANDING_EQUIPMENT: 'Equipment signed',
    DELETE_ACCOUNT_OUTSTANDING_AMMUNITION: 'Ammunition signed',
    DELETE_ACCOUNT_OUTSTANDING_TRANSFERS: 'Open transfer requests',

    // Account Activity Section — credential audit log surfaced to the user
    ACCOUNT_ACTIVITY: 'Account activity',
    ACCOUNT_ACTIVITY_DESCRIPTION:
      'Recent security events on your account — password, phone, and account-deletion changes. If anything looks unfamiliar, contact a system administrator.',
    ACCOUNT_ACTIVITY_EMPTY: 'No security events yet.',
    ACCOUNT_ACTIVITY_LOADING: 'Loading activity...',
    ACCOUNT_ACTIVITY_ERROR: 'Failed to load activity.',
    ACCOUNT_ACTIVITY_RETRY: 'Try again',
    ACCOUNT_ACTIVITY_REFRESH: 'Refresh',
    ACCOUNT_ACTIVITY_IP: 'IP address',
    ACCOUNT_ACTIVITY_DEVICE: 'Device',
    ACCOUNT_ACTIVITY_ACTOR_SELF: 'by you',
    ACCOUNT_ACTIVITY_ACTOR_ADMIN: 'by a system administrator',
    ACCOUNT_EVENT_PASSWORD_CHANGED: 'Password changed',
    ACCOUNT_EVENT_PHONE_CHANGED: 'Phone number changed',
    ACCOUNT_EVENT_EMAIL_CHANGED: 'Email address changed',
    ACCOUNT_EVENT_PHONE_FORCE_RESET: 'Phone number reset by admin',
    ACCOUNT_EVENT_SESSIONS_REVOKED: 'Sessions revoked',
    ACCOUNT_EVENT_ACCOUNT_DELETION_REQUESTED: 'Account deletion requested',
    ACCOUNT_EVENT_ACCOUNT_DELETION_CANCELLED: 'Account deletion cancelled',
    ACCOUNT_EVENT_ACCOUNT_DELETED: 'Account deleted',

    // Revoke other sessions
    REVOKE_SESSIONS: 'Sign out other devices',
    REVOKE_SESSIONS_DESCRIPTION:
      'Signs out every other session on your account. Other devices will have to log in again. This device stays signed in.',
    REVOKE_SESSIONS_CONFIRM_TITLE: 'Sign out other devices?',
    REVOKE_SESSIONS_CONFIRM_BODY:
      'Other devices signed in to your account will need to log in again. This takes effect immediately.',
    REVOKE_SESSIONS_CONFIRM_SUBMIT: 'Sign out other devices',
    REVOKE_SESSIONS_CANCEL: 'Cancel',
    REVOKE_SESSIONS_SUBMITTING: 'Signing out...',
    REVOKE_SESSIONS_SUCCESS: 'Other devices signed out. They will be asked to log in again.',
    REVOKE_SESSIONS_ERROR: 'Sign-out failed. Try again.',
  },
  EQUIPMENT: {
    STATUS_AVAILABLE: 'Available',
    STATUS_SECURITY: 'In security',
    STATUS_REPAIR: 'In repair',
    STATUS_LOST: 'Lost',
    STATUS_PENDING_TRANSFER: 'Pending transfer',
    STATUS_EXCHANGE_REQUESTED: 'Exchange — awaiting approval',
    STATUS_STORED: 'Stored',
    STATUS_RETIRED: 'Returned to army',

    ROW_ACTIONS: {
      REPORT: 'Report',
      TRANSFER: 'Transfer',
      RETURN: 'Return',
      HISTORY: 'History',
      MORE: 'More actions',
      REQUEST_EXCHANGE: 'Request exchange',
      APPROVE_EXCHANGE: 'Approve exchange',
      REJECT_EXCHANGE: 'Reject exchange',
      REPLACE_BY_ANOTHER: 'Replace with another item',
      SEND_TO_STORAGE: 'Send to storage',
      PULL_FROM_STORAGE: 'Pull from storage',
    },

    EXCHANGE: {
      REQUEST_TITLE: 'Request exchange',
      REQUEST_DESCRIPTION: 'Describe why this item needs to be swapped. The signer will approve and assign a new serial.',
      APPROVE_TITLE: 'Approve exchange',
      APPROVE_DESCRIPTION: 'Enter the serial number of the new item that will replace this one.',
      REPLACE_TITLE: 'Replace with another item',
      REPLACE_DESCRIPTION: 'Replace this item with a new serial. The old item will be retired.',
      REJECT_TITLE: 'Reject exchange request',
      REJECT_DESCRIPTION: 'Enter a reason for rejecting the request.',
      REASON_LABEL: 'Reason',
      REASON_PLACEHOLDER: 'Enter a reason...',
      NEW_SERIAL_LABEL: 'New serial number',
      NEW_SERIAL_PLACEHOLDER: 'Enter serial number...',
      SUBMIT_REQUEST: 'Send request',
      SUBMIT_APPROVE: 'Approve and assign new serial',
      SUBMIT_REJECT: 'Reject request',
      SUBMIT_REPLACE: 'Perform exchange',
      CANCEL: 'Cancel',
      REQUEST_SUCCESS: 'Exchange request sent',
      APPROVE_SUCCESS: 'Exchange approved and new item created',
      REJECT_SUCCESS: 'Request rejected',
      REPLACE_SUCCESS: 'Item replaced successfully',
      VALIDATION_REASON_REQUIRED: 'Reason is required',
      VALIDATION_SERIAL_REQUIRED: 'Serial number is required',
      VALIDATION_SERIAL_TAKEN: 'This serial number already exists',
      PREDECESSOR_PILL: 'Created via exchange from {serial}',
    },

    STORAGE: {
      SEND_TITLE: 'Send to storage',
      SEND_DESCRIPTION: 'The item will be marked as stored and excluded from daily checks. It cannot be transferred while in storage.',
      SEND_SUBMIT: 'Send to storage',
      SEND_SUCCESS: 'Item sent to storage',
      PULL_TITLE: 'Pull from storage',
      PULL_DESCRIPTION: 'The item will return to available status.',
      PULL_SUBMIT: 'Pull from storage',
      PULL_SUCCESS: 'Item pulled from storage',
      ROUND_CLOSED_TOOLTIP: 'Round is closed — items cannot be pulled from storage right now',
    },

    SYSTEM_CONFIG: {
      ROUND_OPEN_LABEL: 'Round open',
      ROUND_OPEN_HELP: 'When enabled, users can pull items from storage. Turn off at the end of the round.',
    },
  },
  PROFILE: {
    PHONE_NUMBER_LABEL: 'Phone number',
    TEAM: 'Team',
    ENLISTMENT_CYCLE: 'Enlistment cycle',
    ENLISTMENT_CYCLE_PLACEHOLDER: 'YYYY-MM',
    ADDRESS: 'Address',
    ADDRESS_PLACEHOLDER: 'City, street, house no.',
    EDIT_SECTION: 'Edit',
    EDIT_SECTION_ARIA: 'Edit section',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SAVING: 'Saving...',
    SAVED: 'Saved',
    SAVE_ERROR: 'Save failed. Try again.',
  },
} as const;
