/**
 * POST /api/cron/sweep-account-deletions
 *
 * Hard-delete sweep for accounts whose soft-delete request has aged past the
 * 30-day retention window. Designed for Vercel Cron — see `vercel.json`.
 *
 * Auth: `Authorization: Bearer ${CRON_SECRET}`. The secret is generated by
 * the operator (`openssl rand -hex 32`) and stored in Vercel project env;
 * Vercel injects the same header into scheduled invocations of this route.
 * Verification uses `crypto.timingSafeEqual` to avoid timing-leak attacks.
 *
 * This is system-to-system. Do NOT reuse `getActorFromRequest` — there's no
 * Firebase user behind the request, and we want a separate trust boundary.
 *
 * Production-project gate: refuses with 503 unless the project id is the
 * real prod project. Covers both "missing env" and "running against a
 * preview/dev project" in one check.
 *
 * Query flags:
 *  - `?dryRun=true` — runs the candidate query + per-uid pre-flight, no
 *    Auth/Firestore writes. Strong safety net for the first manual hit.
 *  - `?limit=N` — clamp 1..100, default 25. One run processes at most N
 *    candidates; remaining roll to the next tick.
 *
 * Response: `SweepResult` body, plus `console.log` per-candidate so Vercel
 * function logs carry an audit trail.
 */
import { NextResponse } from 'next/server';
import { timingSafeEqual } from 'crypto';
import { serverSweepAccountDeletions } from '@/lib/db/server/accountDeletionService';

const PROD_PROJECT_ID = 'sayeret-givati-1983';
const DEFAULT_BATCH_LIMIT = 25;

function isAuthorized(request: Request): boolean {
  const expected = process.env.CRON_SECRET;
  if (!expected) return false;
  const header = request.headers.get('authorization') ?? '';
  const presented = header.startsWith('Bearer ') ? header.slice(7) : '';
  if (!presented) return false;
  const a = Buffer.from(presented);
  const b = Buffer.from(expected);
  if (a.length !== b.length) return false;
  try {
    return timingSafeEqual(a, b);
  } catch {
    return false;
  }
}

export async function POST(request: Request) {
  if (!process.env.CRON_SECRET) {
    return NextResponse.json(
      { success: false, error: 'cron_disabled', message: 'CRON_SECRET is not configured' },
      { status: 503 },
    );
  }

  if (process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID !== PROD_PROJECT_ID) {
    return NextResponse.json(
      {
        success: false,
        error: 'wrong_project',
        message: `Cron disabled outside the prod project (current: ${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? 'unset'})`,
      },
      { status: 503 },
    );
  }

  if (!isAuthorized(request)) {
    return NextResponse.json({ success: false, error: 'unauthorized' }, { status: 401 });
  }

  const url = new URL(request.url);
  const dryRun = url.searchParams.get('dryRun') === 'true';
  const limitParam = url.searchParams.get('limit');
  const batchLimit = limitParam ? Math.max(1, Math.min(100, Number(limitParam))) : DEFAULT_BATCH_LIMIT;
  if (limitParam && Number.isNaN(Number(limitParam))) {
    return NextResponse.json(
      { success: false, error: 'bad_limit', message: 'limit must be a number 1..100' },
      { status: 400 },
    );
  }

  console.log('[cron/sweep] starting', { dryRun, batchLimit });
  try {
    const result = await serverSweepAccountDeletions({ dryRun, batchLimit });
    console.log('[cron/sweep] done', {
      examined: result.examined,
      deleted: result.deleted,
      skipped: result.skipped,
      errors: result.errors.length,
      durationMs: result.durationMs,
      dryRun: result.dryRun,
    });
    for (const c of result.candidates) {
      console.log('[cron/sweep] candidate', c);
    }
    return NextResponse.json({ success: true, ...result });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[cron/sweep] FAILED', message);
    return NextResponse.json({ success: false, error: 'sweep_failed', message }, { status: 500 });
  }
}
